  account-app:
    image: chipnesh/account
    environment:
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:admin@registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/mdhr
      - JHIPSTER_SLEEP=30
      - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=search-elasticsearch:9300
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - JAVA_OPTS=-Xmx256m -Xms256m

  audit-app:
    image: chipnesh/audit
    environment:
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:admin@registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/mdhr
      - JHIPSTER_SLEEP=30
      - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=search-elasticsearch:9300
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - JAVA_OPTS=-Xmx256m -Xms256m

  gateway-app:
    image: chipnesh/gateway
    environment:
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:admin@registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/mdhr
      - JHIPSTER_SLEEP=30
      - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=search-elasticsearch:9300
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - JAVA_OPTS=-Xmx256m -Xms256m
    ports:
      - 8080:8080

  organization-app:
    image: chipnesh/organization
    environment:
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:admin@registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/mdhr
      - JHIPSTER_SLEEP=30
      - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=search-elasticsearch:9300
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - JAVA_OPTS=-Xmx256m -Xms256m

  search-elasticsearch:
    image: elasticsearch:2.4.6
    ports:
      - 9300:9300

  registry:
    image: jhipster/jhipster-registry:v3.2.4
    # By default the JHipster Registry runs with the "dev" and "native"
    # Spring profiles.
    # "native" profile means the filesystem is used to store data, see
    # http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html
    environment:
      - SPRING_PROFILES_ACTIVE=prod,git,swagger
      - SECURITY_USER_PASSWORD=admin
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - JHIPSTER_LOGGING_LOGSTASH_ENABLED=true
      - JHIPSTER_LOGGING_LOGSTASH_HOST=logstash
      - JHIPSTER_METRICS_LOGS_ENABLED=true
      - JHIPSTER_METRICS_LOGS_REPORTFREQUENCY=60
      - JAVA_OPTS=-Xmx256m -Xms256m
      - GIT_URI=https://github.com/chipnesh/mdhr/docker
      - GIT_SEARCH_PATHS=central-server-config
    ports:
      - 8761:8761

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6

  kafka:
    image: wurstmeister/kafka:1.0.0
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic-jhipster:1:1"
      JAVA_OPTS: -Xmx1g -Xms512g
    links:
      - zookeeper
    ports:
      - 9092:9092  # Uncomment to make Kafka available externally

  postgresql:
    image: postgres:9.6.5
    environment:
      - POSTGRES_USER=mdhr
      - POSTGRES_PASSWORD=mdhr
      - JAVA_OPTS=-Xmx512m -Xms256m


  elasticsearch:
    image: jhipster/jhipster-elasticsearch:v3.0.1
    ports:
      - 9200:9200
    environment:
      - ES_JAVA_OPTS=-Xmx512m -Xms256m

  logstash:
    image: jhipster/jhipster-logstash:v3.0.1
    environment:
      - INPUT_TCP_PORT=5000
      - INPUT_UDP_PORT=5000
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - LOGSTASH_DEBUG=false
    ports:
      - 5000:5000
      - 5000:5000/udp
    links:
      - elasticsearch

  console:
    image: jhipster/jhipster-console:v3.0.1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - JAVA_OPTS=-Xmx512m -Xms256m
    ports:
      - 5601:5601
    links:
      - elasticsearch

  import-dashboards:
    image: jhipster/jhipster-import-dashboards:v3.0.1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - KIBANA_URL=http://console:5601
    links:
      - elasticsearch

  curator:
    image: jhipster/jhipster-curator:v3.0.1
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - UNIT_COUNT=7
      - UNIT=days
    links:
      - elasticsearch

  zipkin:
    image: jhipster/jhipster-zipkin:v3.0.1
    ports:
      - 9411:9411
    links:
      - elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xmx512m -Xms256m
      - ES_HOSTS=http://elasticsearch:9200
      - ZIPKIN_UI_LOGS_URL=http://localhost:5601/app/kibana#/dashboard/logs-dashboard?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-1h,mode:quick,to:now))&_a=(filters:!(),options:(darkTheme:!f),panels:!((col:1,id:logs-levels,panelIndex:2,row:1,size_x:6,size_y:3,type:visualization),(col:7,columns:!(stack_trace),id:Stacktraces,panelIndex:7,row:1,size_x:4,size_y:3,sort:!('@timestamp',desc),type:search),(col:11,id:Log-forwarding-instructions,panelIndex:8,row:1,size_x:2,size_y:3,type:visualization),(col:1,columns:!(app_name,level,message),id:All-logs,panelIndex:9,row:4,size_x:12,size_y:7,sort:!('@timestamp',asc),type:search)),query:(query_string:(analyze_wildcard:!t,query:'{traceId}')),title:logs-dashboard,uiState:())

    hazelcast-management-center:
        image: hazelcast/management-center:3.9.1
        ports:
            - 8180:8080
