version: '2'
services:
    auth-app:
        image: chipnesh/auth
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/mdhr
            - JHIPSTER_SLEEP=30
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=search-elasticsearch:9300
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
            - JHIPSTER_REGISTRY_PASSWORD=admin
        ports:
            - 8888:8888

    audit-app:
        image: chipnesh/audit
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/mdhr
            - JHIPSTER_SLEEP=30
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=search-elasticsearch:9300
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
            - JHIPSTER_REGISTRY_PASSWORD=admin
    
    gateway-app:
        image: chipnesh/gateway
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/mdhr
            - JHIPSTER_SLEEP=30
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=search-elasticsearch:9300
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
            - JHIPSTER_REGISTRY_PASSWORD=admin
        ports:
            - 8080:8080
    
    organization-app:
        image: chipnesh/organization
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/mdhr
            - JHIPSTER_SLEEP=30
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=search-elasticsearch:9300
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
            - JHIPSTER_REGISTRY_PASSWORD=admin

    search-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: search-elasticsearch
        hostname: search-elasticsearch
    registry:
        extends:
            file: registry.yml
            service: registry
        hostname: registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-server-config/docker-config/
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
        hostname: zookeeper
    kafka:
        extends:
            file: kafka.yml
            service: kafka
        hostname: kafka
        depends_on:
            - zookeeper
    postgresql:
        image: postgres:9.6.5
        environment:
            - POSTGRES_USER=mdhr
            - POSTGRES_PASSWORD=mdhr
        hostname: postgresql
    elasticsearch:
        extends:
            file: console.yml
            service: elasticsearch
        hostname: elasticsearch
    logstash:
        extends:
            file: console.yml
            service: logstash
        depends_on:
            - elasticsearch
        hostname: logstash
    console:
        extends:
            file: console.yml
            service: console
        depends_on:
            - elasticsearch
        hostname: console
    import-dashboards:
        extends:
            file: console.yml
            service: import-dashboards
        depends_on:
            - elasticsearch
    curator:
        extends:
            file: console.yml
            service: curator
        depends_on:
            - elasticsearch
        hostname: curator
    zipkin:
        extends:
            file: console.yml
            service: zipkin
        depends_on:
            - elasticsearch
        hostname: zipkin
    hazelcast-console:
        extends:
            file: hazelcast-management-center.yml
            service: hazelcast-management-center
        hostname: hazelcast-console
